language: android
script: releases/travis_build.sh

after_script:
    - releases/publish_s3.sh

android:
  components:
    #- platform-tools
    #- tools

    - build-tools-22.0.1
    - android-21
    - extra-android-support
    - extra-google-m2repository
    - extra-android-m2repository
